quiz2_main/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :ideas do 
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
 

  get '/', {to: 'ideas#home', as: 'home_page'}
end

quiz2_main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

quiz2_main/app/models/idea.rb
class Idea < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :body, presence: true, uniqueness: true

    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
end

quiz2_main/app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea

    validates :user_id, uniqueness: {scope: :idea_id}
end

quiz2_main/app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :idea

    validates :body, presence: true
end

quiz2_main/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_ideas, through: :like, source: :idea


    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
end

quiz2_main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        current_user ||= User.find_by_id(session[:user_id])
      end
    
      def user_signed_in?
        current_user.present?
      end
    
      def authenticate_user!
        unless user_signed_in?
          flash[:danger] = "Please Sign In"
          redirect_to new_sessions_path
        end
      end
    
      
    
      helper_method :authenticate_user!
      helper_method :current_user
end

quiz2_main/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :authenticate_user!, except: [:home, :index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  def home
  end

  def new
    @idea = Idea.new
  end

  def index
    @ideas = Idea.all
  end

  def show
   @idea = find_idea

   @review = Review.new
   @reviews = @idea.reviews
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user

    if @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def edit
    @idea = find_idea
  end

  def update
    @idea = find_idea

    if @idea.update(idea_params)
      redirect_to(idea_path(@idea))
    else
      render :edit
    end
  end

  def destroy
    @idea = find_idea
    @idea.destroy
    redirect_to(ideas_path)
  end

  private
  def idea_params
    params.require(:idea).permit(:title, :body, :user_id)
  end

  def find_idea
    Idea.find(params[:id])
  end

  def authorize_user!
    @idea = find_idea
    redirect_to home_page_path unless can?(:crud, @idea)
  end
end

quiz2_main/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user!, only: [:destroy]

  def create
    @like = Like.new(user: current_user, idea_id: params[:idea_id])
    @idea = Idea.find(params[:idea_id])
    
    if !can?(:like, @idea)
      flash[:error] = "Cannot like your own idea"
      redirect_to idea_path(@idea)
    else
      @like.save
      redirect_to idea_path(@like.idea)
    end

  end

  def destroy
    @like = Like.find(params[:id])

    @like.destroy

    redirect_to idea_path(@like.idea)
  end

  private
  def authorize_user!
    @like = Like.find_by(id: params[:id])
    redirect_to idea_path(@like.idea) unless can?(:like, @like.idea)
  end
end

quiz2_main/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
  before_action :authorize_user!, only: [:destroy]

  def create
    review = Review.new review_params
    idea = Idea.find(params[:idea_id])

    review.idea = idea
    review.user = current_user
    review.save

    redirect_to idea_path(idea)
  end

  def destroy
    review = Review.find(params[:id])
    review.destroy

    redirect_to idea_path(review.idea)
  end

  private
  def review_params
    params.require(:review).permit(:body)
  end

  def authorize_user!
    @review = Review.find(params[:id])
    redirect_to home_page_path unless can?(:crud, @review)
  end
end

quiz2_main/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    
    end
  
    def create
      user = User.find_by(email: params[:email])
  
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to home_page_path
      else
        flash[:error] = "Username or password is invalid"
        render :new
      end
    end
  
    def destroy
      session[:user_id] = nil
      redirect_to home_page_path
    end
end

quiz2_main/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new user_params
        if @user.save
          redirect_to new_sessions_path
        else
          render :new
        end
      end
    
      private
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
      end
end

quiz2_main/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz2_main/app/helpers/ideas_helper.rb
module IdeasHelper
end

quiz2_main/app/helpers/likes_helper.rb
module LikesHelper
end

quiz2_main/app/helpers/reviews_helper.rb
module ReviewsHelper
end

quiz2_main/app/helpers/sessions_helper.rb
module SessionsHelper
end

quiz2_main/app/helpers/users_helper.rb
module UsersHelper
end

quiz2_main/app/views/ideas/edit.html.erb
<div>
  <div>
    <% if @idea.errors.any? %>
      <ul>
        <% @idea.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div>
    <%= form_with model: @idea, local: true do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

quiz2_main/app/views/ideas/home.html.erb
<h1>Welcome</h1>

quiz2_main/app/views/ideas/index.html.erb
<div>
  <% if !@ideas.nil? %>
    <div>
      <% @ideas.each do |idea| %>
        <div>
          <h3><%= link_to idea.title, idea_path(idea) %></h3>
          <p><%= idea.body %></p>
          <div>
            <h6>By <%= idea.user.first_name %></h6>
            <h6>Likes: <%= idea.likers.count %></h6>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

quiz2_main/app/views/ideas/new.html.erb
<div>
  <div>
    <% if @idea.errors.any? %>
      <ul>
        <% @idea.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div>
    <%= form_with model: @idea, local: true, do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title%>
      </div>
      <div>
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>
      <%= f.submit%>
    <% end %>
  </div>
</div>

quiz2_main/app/views/ideas/show.html.erb
<div>
  <div>
    <div>
      <h3><%= @idea.title %></h3>
      <p><%= @idea.body%></p>
    </div>
    <div>
      <% if can?(:crud, @idea) %>
        <%= link_to "Edit", edit_idea_path(@idea)%>
        <%= link_to "Delete", idea_path(@idea), method: :delete %>
      <% end %>
      <% like = @idea.likes.find_by(user: current_user)%>
      <% if like.nil? %>
        <%= link_to "Like", idea_likes_path(@idea), method: :post %>
      <% else %>
        <%= link_to "Unlike", idea_like_path(@idea, like), method: :delete %>
      <% end %>
    </div>
    <div>
        <h6>By <%= @idea.user.first_name %></h6>
        <h6><%= time_ago_in_words(@idea.created_at) %> ago</h6>
        <h6>Likes - <%= @idea.likers.count %></h6>
    </div>
  </div>
  
  <div>
    <% if @review.errors.messages.any? %>
      <div>
        <ul>
          <% @review.errors.full_messages.each do |err| %>
            <li><%= err %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div>
      <h2>Create review</h2>
      <%= form_with model: @review, url: idea_reviews_path(@idea), local: true do |f| %>
        <div>
          <%= f.label :body%>
          <%= f.text_field :body %>
        </div>
        <%= f.submit "Submit Review"%>
      <% end %>
    </div>
    <% if !@reviews.nil? %>
      <div>
        <% @reviews.each do |review| %>
          <div>
            <p><%= review.body %></p>
            <% if can?(:crud, review) %>
              <%= link_to "Delete", idea_review_path(@idea, review), method: :delete %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

quiz2_main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz2Main</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">IdeaDeck</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/ideas/new">New</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/ideas">Ideas</a>
          </li>
        </ul>
        <div class="welcome-container">
          <% if current_user.present? %>
            <h6 class="name-heading">Hello <%= current_user.first_name %> !</h6>
          <% end %>
        </div>
        <ul class="navbar-nav">
          <% if current_user.present? %>
            <li class="nav-item">
              <%= link_to "Sign Out", sessions_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign In", new_sessions_path %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

quiz2_main/app/views/users/new.html.erb
<div>
  <div>
    <% if @user.errors.messages.any? %>
      <ul>
        <% @user.errors.full_messages.each do |err| %>
          <li><%= err %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div>
    <%= form_with model: @user, local: true do |f| %>
      <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div>
      <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div>
      <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.text_field :password %>
      </div>
      <div>
        <%= f.label :password_confirmation %>
        <%= f.text_field :password_confirmation %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>